name: product_repo
description: "Dart package which maintain product repository"
publish_to: 'none'
version: 0.1.0


environment:
  sdk: ">=3.3.0<4.0.0"

dependencies:
  
  cloud_firestore: ^5.0.0
  equatable: ^2.0.5
  file_picker: ^8.0.3
  firebase_core: ^3.0.0
  firebase_storage: ^12.0.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true