name: admin_panel
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-18.0.dev <4.0.0'

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  file_picker: ^8.0.3
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_storage: ^12.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.0
  go_router: ^14.1.4
  provider: ^6.1.2
  #custom repository
 
  user_repo:
    path: 'packages/user_repo'
  product_repo:
    path: 'packages/product_repo'
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
