// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjvg2cJNRAlTwQ15fbvepelr92GiDeQGQ',
    appId: '1:452236619238:web:48075cb0609e2c9b1e3a27',
    messagingSenderId: '452236619238',
    projectId: 'ecommerce-8ea16',
    authDomain: 'ecommerce-8ea16.firebaseapp.com',
    storageBucket: 'ecommerce-8ea16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNXajb8R2tByCB0GACd7_5kXIL-BnFgd4',
    appId: '1:452236619238:android:1567d809e239a7441e3a27',
    messagingSenderId: '452236619238',
    projectId: 'ecommerce-8ea16',
    storageBucket: 'ecommerce-8ea16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-UxnBTM51059wq15l8P8rO6iHJPr5m7A',
    appId: '1:452236619238:ios:196633376ce2624c1e3a27',
    messagingSenderId: '452236619238',
    projectId: 'ecommerce-8ea16',
    storageBucket: 'ecommerce-8ea16.appspot.com',
    iosBundleId: 'com.example.adminPanel',
  );
}
