name: user_repo
description: "Dart package which maintain user repository"
publish_to: 'none'
version: 0.1.0


environment:
  sdk: ">=3.3.0<4.0.0"

dependencies:
  cloud_firestore: ^5.0.0
  equatable: ^2.0.5
  firebase_auth: ^5.0.0
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true